version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: sh -c "make migrate && make run/devserver"
    env_file:
      - api.env
    restart: "on-failure"
    logging:
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      PYTHONASYNCIODEBUG: "1"
      PYTHONDEVMODE: "1"
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"
      GRASP_API_DB_HOST: "postgres"
      # GRASP_API_DB_HOST: {GRASP_API_DB_HOST}


  postgres:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_PASSWORD: "qwerty123"
      POSTGRES_DB: "grasp_api"
      # POSTGRES_PASSWORD: ${GRASP_API_DB_PASSWORD}
      # POSTGRES_DB: ${GRASP_API_DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data_grasp


volumes:
  postgres-db:
