"""autogenerated

Revision ID: daee4898f3bf
Revises: 
Create Date: 2024-06-09 23:08:51.022145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "daee4898f3bf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "example",
        sa.Column("pk_example", sa.String(length=50), nullable=False),
        sa.Column("string_example", sa.String(length=128), nullable=True),
        sa.Column("string2_example", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("pk_example"),
    )
    op.create_index(
        op.f("ix_example_string2_example"),
        "example",
        ["string2_example"],
        unique=False,
    )
    op.create_table(
        "sensor_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sensor_id", sa.String(length=10), nullable=True),
        sa.Column("dwell_time", sa.String(length=10), nullable=True),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sensor_data")
    op.drop_index(op.f("ix_example_string2_example"), table_name="example")
    op.drop_table("example")
    # ### end Alembic commands ###
